name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.14
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Assembly
        run: sbt +assembly
        env:
          LENSES_TAG_NAME: ${{ steps.get_tag.outputs.VERSION }}
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/scala-2.12/secret-provider_2.12-${{ steps.get_tag.outputs.VERSION }}-all.jar
            target/scala-2.13/secret-provider_2.13-${{ steps.get_tag.outputs.VERSION }}-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LENSES_TAG_NAME: ${{ steps.get_tag.outputs.VERSION }}
